### ISSUE TITLE
优缺点我都来说一下吧

### ISSUE THREAD

**Issue by Allureglorious** [octopusring/Light-Ink#2]
### 优点：

> ui及交互相当优秀，自带的阅读格式确实很不错，不需要再调，其余设置都符合极简以及我的xp。在我体验了上百款阅读app，这款能排前三。最突出的优点莫过于主题了，几十种主题相当漂亮，不会让你感到千篇一律，很多主题相当新颖别致。我最喜欢的功能全屏下一页、仿真翻页都加入了，目前体验下来这是一款我愿意付费的app！

### 缺点：

> 支持的格式比较少，epub导入会失去原格式，导入文件不能记住上次文件夹位置，翻页偶尔会出现瞬间的黑页或白页。书架不支持多选、无法整理书籍，适合阅读量不大的人群。
**最后最最大的缺点是不支持搜索！！！**

**Comment by Liloupar** [comment]
多选在右边, 那边可以编辑/多选 等整理用操作
