### ISSUE TITLE
翻页区域设置问题

### ISSUE THREAD

**Issue by wunaier** [octopusring/Light-Ink#4]
没有找到设置翻页区域的设置，点击屏幕左侧和右侧都是向下翻页

**Comment by Liloupar** [comment]
@wunaier 
看下是否误开启了全屏点击下一页

**Comment by wunaier** [comment]
感谢您的回复，确实是这个原因
________________________________
发件人: Liloupar ***@***.***>
发送时间: 2024年9月25日 10:37
收件人: octopusring/Light-Ink ***@***.***>
抄送: wunaier ***@***.***>; Mention ***@***.***>
主题: Re: [octopusring/Light-Ink] 翻页区域设置问题 (Issue #4)


Closed #4<https://github.com/octopusring/Light-Ink/issues/4> as completed.

―
