### ISSUE TITLE
摘录语句显示数目问题

### ISSUE THREAD

**Issue by Arwenleo** [octopusring/Light-Ink#5]
版本：1.10.6
书籍格式：TXT文档
问题：书籍中的摘录超过20条后，从“摘抄”页面进入只能显示最新的20条。在书籍中确认过，更旧的摘抄仍旧存在，只是无法从“摘抄”页面找到。由于不存在其他导航途径，等于说早于最新20条的摘录不见了，除非从头重新一页页翻阅。
另外一个小建议：提供文本划线后同时添加笔记的功能。

**Comment by Liloupar** [comment]
小建议要等一个flutter pr的落地

refer: https://github.com/flutter/flutter/pull/154202?notification_referrer_id=NT_kwDOANV6i7QxMjEzNzExNjI5MzoxMzk5MDUzOQ#issuecomment-2406202870

**Comment by Liloupar** [comment]
已修复 @Arwenleo
