### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Allureglorious** [octopusring/Light-Ink#6]
## 希望能优化一下：

> 1、ios系统下面的横杠无法去掉；
> 2、得联网，关了网络无法统计时间；
> 3、会自动上传数据，担心隐私问题；
> 4、无法清理缓存；
> 5、摘抄及阅读记录无法删除；
> 6、邮箱无法更改；
> 7、标题与内容间距相差过大；
> 8、个人信息包括头像只能改微信的才能同步等…
### 希望及时更新。

**Comment by Liloupar** [comment]
4是什么意思? 没太理解

另外应该无需清除缓存, 没回复我先close了
