### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Allureglorious** [octopusring/Light-Ink#8]
1. 无法搜索*字符，其它字符待验证；
2. 目录拖动条完全不准确，不是靠上就是靠下，很难用，希望及时修复

**Comment by Liloupar** [comment]
问题1帮忙发个有问题的文件吧

AllureLuv ***@***.***>于2024年11月21日 周四22:12写道：

**Comment by Liloupar** [comment]
没回复先close了
